bug: don't rollback non-spanner connections on reset
This is the simplest way to address bug #706 and address the
`AttributeError: 'Connection' object has no attribute 'rollback'`
I'm seeing when connections from BigQuery engines get caught by this
event handler.

I think we should be able to rely on SQLAlchemy's [reset on
return](https://docs.sqlalchemy.org/en/20/core/pooling.html#reset-on-return)
behaviour to rollback transactions when they're reset rather than call
rollback ourselves. That behaviour is also something end users can
configure, so it'd be good to respect their settings if they disable
the behaviour.

Fixes: #706